version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UI_ENV_FILE: .env.dev
    ports:
      - '8080:8080'
    mem_limit: "1g"
    mem_reservation: "512m"
    cpus: 1
    cpuset: "2"
    healthcheck:
      test: curl -Is localhost:8080 | head -n 1 | grep 200 || exit 1
      interval: 10s
      timeout: 2s
      retries: 10