server:
  http2:
    enabled: true
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
spring:
  application:
    name: FullStack (API)
  main:
    lazy-initialization: true
  resources:
    cache:
      cachecontrol:
        max-age: 36000 # 10 min
        must-revalidate: true # important for react app.
  port: 8080
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null
management:
  endpoints:
    web:
      exposure:
        include: health,status
security:
  enabled: true
  apiKey: ${SECURITY_API_KEY:}
  rate-limit: 10 # capacity per minutes
  eviction: 1 # hours / cleanup of old stuff
  cors:
    - "http://localhost:3000"
  publics:
    - "/api/hello"
    - "/actuator/health"
status:
  enabled: true
  logs-size: 100
logging:
  file:
    name: "./logs/app.log"
    max-history: 1
    max-size: 100KB
  level:
    root: ERROR
    org.springframework: ERROR
    com.creativeyann17.api: INFO
    org.hibernate: ERROR
