server:
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
spring:
  resources:
    cache:
      cachecontrol:
        max-age: 36000 # 10 min
        must-revalidate: true # important for react app.
  port: 8080
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null
springdoc:
  swagger-ui:
    enabled: false
    path: /swagger-ui
  api-docs:
    enabled: false
    path: /openapi
management:
  endpoint:
    health:
      probes:
        enabled: true
logging:
  level:
    root: ERROR
    org.springframework: ERROR
    com.creativeyann17: INFO
    org.hibernate: ERROR